- name: Pipenv Tox-based Tests
  hosts: all
  tasks:
    - name: Make sure pipenv and tox are installed
      shell: pip install --user pipenv tox
    - name: Make sure ansible is installed
      shell: pip install --user ansible
      when: install_ansible | default(True) | bool
    - name: Run tox
      args:
        chdir: "{{ zuul.project.src_dir }}"
      command: "tox"
